//Exercise on page 727

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

public class JHelloFrame extends JFrame implements ActionListener
{
	//Create new components for the class
	JLabel question = new JLabel("What is your name?");
	Font bigFont = new Font("Arial", Font.BOLD, 16);
	JTextField answer = new JTextField(10);
	JButton pressMe = new JButton("Click Me!");
	JLabel greeting = new JLabel("");
	//Variables and Constants
	final int WIDTH = 275;
	final int HEIGHT = 225;
	
	//Constructor method for this class ^^
	public JHelloFrame()
	{
		super("Hello Frame");
		setSize(WIDTH, HEIGHT);
		setLayout(new FlowLayout());
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		//Set font before you add the text(Common sense stupid)
		question.setFont(bigFont);
		greeting.setFont(bigFont);
		//Add components form class ^^ to the frame
		add(question);
		add(answer);
		add(pressMe);
		add(greeting);
		// add event listener to the button element
		pressMe.addActionListener(this);
	}
	
	//Method that responds to the event generated by addEventListener
	@Override
	public void actionPerformed(ActionEvent e)
	{
		String name = answer.getText();
		String greet = "Hello, " + name;
		greeting.setText(greet);
	}
}